language: go
go:
  - 1.9
  - tip
install:
  - go get golang.org/x/oauth2
before_script:
  - wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
  - unzip -q google_appengine_1.8.9.zip
